output "postgres_endpoint" {
  description = "RDS endpoint host."
  value       = aws_db_instance.main.address
}

output "postgres_port" {
  description = "RDS port."
  value       = aws_db_instance.main.port
}

output "postgres_database_name" {
  description = "Initial database name (PG_DB)."
  value       = aws_db_instance.main.db_name
}

output "postgres_username" {
  description = "Master username (PG_USER)."
  value       = aws_db_instance.main.username
}

output "postgres_password" {
  description = "Master password (PG_PASSWORD). Generated by Terraform and therefore present in state -- keep the state bucket encrypted and access-controlled, and rotate this into Secrets Manager as the operational copy."
  value       = random_password.postgres.result
  sensitive   = true
}

output "postgres_connection_uri" {
  description = "Full connection URI for POSTGRES_URI / DATABASE_URI. sslmode=require because rds.force_ssl is on."
  value       = "postgresql://${aws_db_instance.main.username}:${urlencode(random_password.postgres.result)}@${aws_db_instance.main.address}:${aws_db_instance.main.port}/${aws_db_instance.main.db_name}?sslmode=require"
  sensitive   = true
}

output "redis_primary_endpoint" {
  description = "ElastiCache primary endpoint host."
  value       = aws_elasticache_replication_group.main.primary_endpoint_address
}

output "redis_auth_token" {
  description = "ElastiCache AUTH token."
  value       = random_password.redis_auth.result
  sensitive   = true
}

output "redis_connection_uri" {
  description = "Full connection URI for REDIS_URI. rediss:// because transit encryption is enabled."
  value       = "rediss://:${urlencode(random_password.redis_auth.result)}@${aws_elasticache_replication_group.main.primary_endpoint_address}:6379/0"
  sensitive   = true
}

output "postgres_security_group_id" {
  description = "Security group guarding Postgres."
  value       = aws_security_group.postgres.id
}

output "efs_file_system_id" {
  description = "EFS file system id for the shared Hugging Face weight cache."
  value       = aws_efs_file_system.models.id
}

output "efs_access_point_id" {
  description = "EFS access point id, referenced by the models PersistentVolume."
  value       = aws_efs_access_point.models.id
}
